### ISSUE TITLE
WeChatUtil.java代码里面对回调地址的URLEncode的问题，会导致redirect_uri不一致的问题

### ISSUE THREAD

**Issue by Mosicol** [cxhello/springboot-wechat#1]
有问题的代码：
weChatRedirectUrl = URLEncoder.encode(weChatRedirectUrl, CHARSET_NAME);
因为这样在多次使用的情况下，会迭代进行URLEncode
只需要定义一个新的变量即可
public static String generateWxQrCode() {
        try {
            weChatRedirectUrl_encode = URLEncoder.encode(weChatRedirectUrl, CHARSET_NAME);
        } catch (UnsupportedEncodingException e) {
            logger.error("System error", e);
        }
        return String.format(LOGIN_URL, weChatAppId, weChatRedirectUrl_encode, STATE);
    }

**Comment by cxhello** [comment]
对，确实有问题，第二次调用或者后续调用的时候会使用前一次encode后的值，weChatRedirectUrl这个变量会被修改掉。
